In [1]:
from pyspark.sql import SQLContext, Row

In [2]:
from pyspark.sql import SparkSession,Row
import collections

In [3]:
spark = SparkSession.builder.config("spark.sql.warehouse.dir").appName("SparkSQL").getOrCreate()

In [4]:
def mapper(line):
    fields = line.split(',')
    return Row(ID=int(fields[0]), name=str(fields[1].encode("utf-8")), age=int(fields[2]), numFriends=int(fields[3]))

In [5]:
lines = spark.sparkContext.textFile("dbfs:/FileStore/tables/fakefriends.csv")
people = lines.map(mapper)

In [6]:
schemaPeople = spark.createDataFrame(people).cache()
schemaPeople.createOrReplaceTempView("people")

In [7]:
teenagers = spark.sql("SELECT * FROM people WHERE age >= 13 AND age <= 19")

In [8]:
for teen in teenagers.collect():
  print(teen)

In [9]:
schemaPeople.groupBy("age").count().orderBy("count").show()

In [10]:
teenagers.groupBy("age").count().max("count").show()

In [11]:
%fs ls /FileStore/tables/

path,name,size
dbfs:/FileStore/tables/Book.txt,Book.txt,264875
dbfs:/FileStore/tables/README,README,6750
dbfs:/FileStore/tables/allbut.pl,allbut.pl,716
dbfs:/FileStore/tables/countofsessions.csv,countofsessions.csv,127520
dbfs:/FileStore/tables/exportboothtypes.csv,exportboothtypes.csv,373291
dbfs:/FileStore/tables/fakefriends.csv,fakefriends.csv,8754
dbfs:/FileStore/tables/mku.sh,mku.sh,643
dbfs:/FileStore/tables/u.data,u.data,1979173
dbfs:/FileStore/tables/u.genre,u.genre,202
dbfs:/FileStore/tables/u.info,u.info,36
dbfs:/FileStore/tables/u.item,u.item,236344
dbfs:/FileStore/tables/u.user,u.user,22628
dbfs:/FileStore/tables/u1.base,u1.base,1586544
dbfs:/FileStore/tables/u1.test,u1.test,392629
dbfs:/FileStore/tables/u2.base,u2.base,1583948
dbfs:/FileStore/tables/u2.test,u2.test,395225
dbfs:/FileStore/tables/u3.base,u3.base,1582546
dbfs:/FileStore/tables/u3.test,u3.test,396627
dbfs:/FileStore/tables/u4.base,u4.base,1581878
dbfs:/FileStore/tables/u4.test,u4.test,397295
dbfs:/FileStore/tables/u5.base,u5.base,1581776
dbfs:/FileStore/tables/u5.test,u5.test,397397
dbfs:/FileStore/tables/u_occupation-f60a8,u_occupation-f60a8,193
dbfs:/FileStore/tables/ua.base,ua.base,1792501
dbfs:/FileStore/tables/ua.test,ua.test,186672
dbfs:/FileStore/tables/ub.base,ub.base,1792476
dbfs:/FileStore/tables/ub.test,ub.test,186697

In [12]:
#creating datframe from list of tuples 
from pyspark.sql import Row
from pyspark.sql.types import *
l = [('Ankit',25),('Jalfaizy',22),('saurabh',20),('Bala',26)]
rdd = sc.parallelize(l)
persons = rdd.map(lambda x: Row(name = x[0], age = int(x[1])))
schemapersons = sqlContext.createDataFrame(persons)
schemapersons.registerTempTable('schemapersons_table')

In [13]:

sqlContext.sql("select * from schemapersons_table where age > 22").show()
#type(rdd)
#type(schemapersons)

In [14]:
rdd.take(4).foreach()

In [15]:
counter = 0
rdd = sc.parallelize(data)

# Wrong: Don't do this!!
def increment_counter(x):
    global counter
    counter += x
rdd.foreach(increment_counter)

print("Counter value: ", counter)

In [16]:
#  creating datframe from CSV
import pandas as pd
from pyspark.sql.types import *
csvdataframe = sqlContext.read.format("csv").options(header = True ,inferSchema = True)
display(csvdataframe)

#schema = StructType([StructField("ID", IntegerType(), True),StructField("name", StringType(), True),StructField("age", IntegerType(), True), StructField("numfriends", IntegerType(), True)])
#csvdatframe2 = sqlContext.createDataFrame(pd_df, schema = schema)

In [17]:
CREATE TABLE fakefriends
  USING csv
  OPTIONS (path "dbfs:/FileStore/tables/fakefriends.csv", header "true", mode "FAILFAST")

In [18]:
train = sqlContext.load(source="com.databricks.spark.csv", path = 'PATH/train.csv', header = True,inferSchema = True)

In [19]:
#reading the extrenal text file into the rdd performng the basic transformations

lines = sc.textFile("dbfs:/FileStore/tables/Book.txt")
def clean(l):
  fields = l.split(' ')
  return(fields)
  
pairs = lines.flatMap(lambda x : x.split(" ")).filter(lambda x: len(x) > 3).map(lambda  s : (s, 1))

pairs2 = pairs.reduceByKey(lambda x,y: x+y).collect()


for i in pairs2:
  print(i)
#pairs2 = pairs.mapValues(lambda s: (s, 1))
#pairs2.reduceByKey(lambda x,y: x+y).collect()

In [20]:
ds.flatMap(x => x.split(" "))

In [21]:
from pyspark.sql.types import *
schema = StructType([StructField('Id',IntegerType(),True),
                     StructField('Name',StringType(),True),
                     StructField('Age',IntegerType(), True),
                     StructField('Friends',IntegerType(),True)])

df = spark.read.format('csv').option('header','false').schema(schema).load('dbfs:/FileStore/tables/fakefriends.csv')
display(df)

Id,Name,Age,Friends
0,Will,33,385
1,Jean-Luc,26,2
2,Hugh,55,221
3,Deanna,40,465
4,Quark,68,21
5,Weyoun,59,318
6,Gowron,37,220
7,Will,54,307
8,Jadzia,38,380
9,Hugh,27,181
10,Odo,53,191
11,Ben,57,372
12,Keiko,54,253
13,Jean-Luc,56,444
14,Hugh,43,49
15,Rom,36,49
16,Weyoun,22,323
17,Odo,35,13
18,Jean-Luc,45,455
19,Geordi,60,246
20,Odo,67,220
21,Miles,19,268
22,Quark,30,72
23,Keiko,51,271
24,Julian,25,1
25,Ben,21,445
26,Julian,22,100
27,Leeta,42,363
28,Martok,49,476
29,Nog,48,364
30,Keiko,50,175
31,Miles,39,161
32,Nog,26,281
33,Dukat,53,197
34,Jean-Luc,43,249
35,Beverly,27,305
36,Kasidy,32,81
37,Geordi,58,21
38,Deanna,64,65
39,Morn,31,192
40,Odo,52,413
41,Hugh,67,167
42,Brunt,54,75
43,Guinan,58,345
44,Nerys,35,244
45,Dukat,52,77
46,Morn,25,96
47,Brunt,24,49
48,Nog,20,1
49,Ezri,40,254
50,Quark,51,283
51,Lwaxana,36,212
52,Beverly,19,269
53,Geordi,62,31
54,Brunt,19,5
55,Keiko,41,278
56,Gowron,44,194
57,Odo,57,294
58,Hugh,59,158
59,Morn,59,284
60,Geordi,20,100
61,Kasidy,62,442
62,Keiko,69,9
63,Jean-Luc,58,54
64,Elim,31,15
65,Guinan,52,169
66,Geordi,21,477
67,Jadzia,48,135
68,Guinan,33,74
69,Jean-Luc,30,204
70,Brunt,52,393
71,Geordi,45,184
72,Kasidy,22,179
73,Brunt,20,384
74,Leeta,65,208
75,Morn,40,459
76,Will,62,201
77,Weyoun,40,407
78,Data,61,337
79,Leeta,58,348
80,Dukat,67,445
81,Jadzia,54,440
82,Hugh,57,465
83,Geordi,32,308
84,Ben,28,311
85,Quark,66,383
86,Hugh,55,257
87,Ezri,31,481
88,Ben,66,188
89,Worf,24,492
90,Kasidy,33,471
91,Rom,46,88
92,Gowron,54,7
93,Elim,46,63
94,Morn,62,133
95,Odo,29,173
96,Ezri,25,233
97,Nerys,69,361
98,Will,44,178
99,Keiko,69,491
100,Jean-Luc,61,460
101,Morn,67,123
102,Dukat,40,18
103,Ezri,61,2
104,Dukat,32,142
105,Morn,50,417
106,Beverly,18,499
107,Will,64,419
108,Leeta,25,274
109,Quark,53,417
110,Nog,64,137
111,Nerys,37,46
112,Morn,25,13
113,Quark,41,244
114,Worf,33,275
115,Dukat,18,397
116,Ben,69,75
117,Rom,52,487
118,Ben,28,304
119,Worf,29,344
120,Jean-Luc,68,264
121,Deanna,35,355
122,Data,45,400
123,Jadzia,45,439
124,Data,47,429
125,Rom,66,284
126,Brunt,26,84
127,Miles,40,284
128,Julian,34,221
129,Kasidy,45,252
130,Gowron,67,350
131,Hugh,65,309
132,Odo,46,462
133,Quark,19,265
134,Ben,45,340
135,Rom,42,427
136,Will,19,335
137,Martok,28,32
138,Dukat,32,384
139,Nog,36,193
140,Elim,64,234
141,Miles,36,424
142,Guinan,59,335
143,Data,60,124
144,Miles,22,93
145,Leeta,45,470
146,Nerys,58,174
147,Quark,61,373
148,Nerys,39,248
149,Beverly,49,340
150,Nerys,55,313
151,Keiko,54,441
152,Kasidy,54,235
153,Morn,63,342
154,Geordi,40,389
155,Beverly,50,126
156,Deanna,44,360
157,Dukat,34,319
158,Odo,31,340
159,Kasidy,67,438
160,Beverly,58,112
161,Odo,39,207
162,Ezri,59,14
163,Nerys,67,204
164,Will,31,172
165,Leeta,26,282
166,Lwaxana,25,10
167,Quark,48,57
168,Martok,68,112
169,Beverly,53,92
170,Jean-Luc,68,490
171,Weyoun,29,126
172,Kasidy,55,204
173,Leeta,23,129
174,Deanna,47,87
175,Will,38,459
176,Worf,55,474
177,Brunt,67,316
178,Kasidy,26,381
179,Elim,37,426
180,Kasidy,30,108
181,Rom,43,404
182,Weyoun,26,145
183,Ben,47,488
184,Julian,44,84
185,Weyoun,48,287
186,Miles,31,109
187,Nerys,47,225
188,Keiko,54,369
189,Quark,62,23
190,Geordi,60,294
191,Nog,40,349
192,Jadzia,45,497
193,Nerys,60,125
194,Kasidy,38,2
195,Ben,30,376
196,Data,38,173
197,Leeta,38,76
198,Brunt,48,381
199,Hugh,38,180
200,Kasidy,21,472
201,Ezri,23,174
202,Lwaxana,63,469
203,Ezri,46,125
204,Deanna,64,164
205,Morn,69,236
206,Will,21,491
207,Lwaxana,41,206
208,Nog,37,271
209,Brunt,27,174
210,Data,33,245
211,Ben,61,73
212,Geordi,55,284
213,Worf,28,312
214,Miles,32,182
215,Will,22,6
216,Brunt,34,116
217,Keiko,29,260
218,Gowron,66,350
219,Lwaxana,26,345
220,Jean-Luc,41,394
221,Dukat,27,150
222,Rom,34,346
223,Odo,40,406
224,Keiko,44,277
225,Elim,19,106
226,Lwaxana,37,207
227,Ezri,40,198
228,Martok,26,293
229,Gowron,24,150
230,Beverly,54,397
231,Ezri,59,42
232,Worf,68,481
233,Gowron,67,70
234,Deanna,49,22
235,Elim,57,8
236,Brunt,62,442
237,Nerys,61,469
238,Deanna,25,305
239,Nog,48,345
240,Deanna,46,154
241,Quark,45,332
242,Data,25,101
243,Martok,61,68
244,Dukat,21,471
245,Jean-Luc,28,174
246,Leeta,41,260
247,Ezri,52,338
248,Dukat,21,138
249,Nerys,66,41
250,Hugh,36,342
251,Rom,55,57
252,Will,36,174
253,Leeta,69,116
254,Ezri,67,79
255,Deanna,60,324
256,Worf,32,412
257,Data,51,161
258,Worf,68,217
259,Kasidy,29,11
260,Brunt,38,96
261,Jadzia,40,172
262,Will,51,334
263,Martok,40,33
264,Julian,29,228
265,Gowron,27,471
266,Jean-Luc,66,496
267,Dukat,49,106
268,Ezri,26,298
269,Beverly,55,289
270,Data,44,353
271,Morn,25,446
272,Quark,29,367
273,Data,51,493
274,Julian,64,244
275,Will,47,13
276,Dukat,54,462
277,Hugh,46,300
278,Data,44,499
279,Beverly,23,133
280,Nerys,26,492
281,Worf,21,89
282,Geordi,32,404
283,Dukat,65,443
284,Nog,26,269
285,Data,43,101
286,Lwaxana,30,384
287,Beverly,64,396
288,Hugh,56,354
289,Ezri,30,221
290,Beverly,62,290
291,Dukat,23,373
292,Nog,63,380
293,Deanna,23,65
294,Leeta,38,410
295,Nerys,40,56
296,Data,38,454
297,Ben,45,395
298,Guinan,57,207
299,Rom,57,311
300,Beverly,49,147
301,Weyoun,28,108
302,Beverly,37,263
303,Deanna,46,319
304,Will,19,404
305,Quark,29,182
306,Beverly,23,323
307,Keiko,41,340
308,Morn,45,59
309,Geordi,67,153
310,Odo,68,189
311,Martok,43,48
312,Jadzia,61,421
313,Dukat,59,169
314,Geordi,36,168
315,Weyoun,25,208
316,Hugh,64,391
317,Guinan,59,439
318,Deanna,35,251
319,Leeta,30,476
320,Worf,62,450
321,Data,44,61
322,Rom,58,92
323,Nog,29,236
324,Miles,56,343
325,Keiko,51,492
326,Beverly,46,407
327,Julian,20,63
328,Deanna,62,41
329,Dukat,67,35
330,Ezri,33,356
331,Martok,30,17
332,Julian,55,362
333,Ben,29,207
334,Leeta,40,7
335,Odo,27,337
336,Gowron,47,4
337,Miles,58,10
338,Will,28,180
339,Morn,66,305
340,Nerys,57,275
341,Data,18,326
342,Guinan,46,151
343,Odo,26,254
344,Data,30,487
345,Ezri,31,394
346,Hugh,29,329
347,Geordi,32,24
348,Weyoun,33,460
349,Kasidy,20,277
350,Nog,55,464
351,Keiko,54,72
352,Deanna,27,53
353,Julian,64,499
354,Kasidy,69,15
355,Keiko,46,352
356,Weyoun,67,149
357,Brunt,26,7
358,Will,52,276
359,Nog,54,442
360,Nerys,39,68
361,Worf,68,206
362,Ezri,39,120
363,Dukat,41,397
364,Lwaxana,54,115
365,Brunt,65,430
366,Keiko,19,119
367,Data,39,106
368,Elim,26,383
369,Quark,48,266
370,Jadzia,53,86
371,Guinan,31,435
372,Brunt,62,273
373,Quark,19,272
374,Nog,68,293
375,Hugh,66,201
376,Gowron,23,392
377,Beverly,18,418
378,Guinan,47,97
379,Data,60,304
380,Brunt,35,65
381,Nog,38,95
382,Worf,66,240
383,Data,69,148
384,Martok,67,355
385,Beverly,57,436
386,Data,35,428
387,Will,43,335
388,Nog,30,184
389,Weyoun,38,38
390,Martok,22,266
391,Ben,64,309
392,Data,64,343
393,Quark,50,436
394,Keiko,23,230
395,Jean-Luc,56,15
396,Keiko,67,38
397,Quark,69,470
398,Lwaxana,26,124
399,Beverly,24,401
400,Data,29,128
401,Jean-Luc,42,467
402,Hugh,58,98
403,Weyoun,21,224
404,Kasidy,18,24
405,Nog,56,371
406,Ben,57,121
407,Miles,36,68
408,Dukat,62,496
409,Nog,19,267
410,Odo,35,299
411,Lwaxana,58,22
412,Jadzia,53,451
413,Hugh,45,147
414,Martok,56,313
415,Quark,30,65
416,Nerys,33,294
417,Julian,37,106
418,Guinan,32,212
419,Kasidy,55,176
420,Jadzia,26,391
421,Will,40,261
422,Ben,67,292
423,Will,44,388
424,Keiko,55,470
425,Quark,33,243
426,Worf,24,77
427,Brunt,28,258
428,Lwaxana,68,423
429,Jean-Luc,63,345
430,Geordi,36,493
431,Quark,36,343
432,Brunt,45,54
433,Ezri,38,203
434,Deanna,57,289
435,Guinan,42,275
436,Geordi,57,229
437,Morn,59,221
438,Nog,42,95
439,Data,18,417
440,Elim,48,394
441,Jadzia,38,143
442,Nog,46,105
443,Geordi,64,175
444,Keiko,18,472
445,Guinan,40,286
446,Quark,32,41
447,Julian,38,34
448,Nerys,48,439
449,Data,52,419
450,Weyoun,37,234
451,Martok,28,34
452,Ezri,58,6
453,Julian,44,337
454,Weyoun,52,456
455,Elim,33,463
456,Ezri,37,471
457,Worf,51,81
458,Elim,44,335
459,Geordi,26,84
460,Hugh,47,400
461,Geordi,41,236
462,Nerys,23,287
463,Keiko,40,220
464,Beverly,25,485
465,Morn,53,126
466,Brunt,33,228
467,Weyoun,42,194
468,Ezri,46,227
469,Brunt,55,271
470,Deanna,38,160
471,Brunt,52,273
472,Nog,27,154
473,Morn,35,38
474,Keiko,34,48
475,Ben,52,446
476,Jean-Luc,28,378
477,Gowron,50,119
478,Dukat,41,62
479,Kasidy,44,320
480,Geordi,43,428
481,Elim,32,97
482,Ben,48,146
483,Hugh,57,99
484,Leeta,22,478
485,Rom,47,356
486,Elim,49,17
487,Brunt,69,431
488,Nog,61,103
489,Odo,33,410
490,Nerys,65,101
491,Rom,60,2
492,Dukat,19,36
493,Hugh,23,357
494,Kasidy,18,194
495,Data,46,155
496,Gowron,39,275
497,Lwaxana,34,423
498,Jadzia,62,36
499,Leeta,62,12

In [22]:
temptable = ''
df.createOrReplaceTempView('temptable')

In [23]:
df5 = spark.sql("select * from temptable")
df5.collect()

In [24]:
df4 = spark.table("temptable")
sorted(df4.collect()) == sorted(df5.collect())

In [25]:
#udf
spark.udf.register('countoffriends',lambda x: len(x))
spark.sql('select countoffriends(_c2) from temptable').collect()

In [26]:
from pyspark.sql.types import * 
from pyspark.sql.functions import udf
slen = udf(lambda s: len(s), IntegerType())
_ = spark.udf.register("slen",slen)
spark.sql('select slen(_c2) from temptable').collect()

In [27]:
from pyspark.sql.functions import pandas_udf,PandasUDFType
pandas_udf('integer',PandasUDFType.GROUPED_AGG)
def sum_udf(v):
  return v.sum()

In [28]:
_= spark.udf.register("sum_udf", sum_udf)

In [29]:
q = 'select sum_udf(_c3),_c1 from temptable group by _c1'
  spark.sql(q).collect()

In [30]:
%sql
select * from temptable

_c0,_c1,_c2,_c3
0,Will,33,385
1,Jean-Luc,26,2
2,Hugh,55,221
3,Deanna,40,465
4,Quark,68,21
5,Weyoun,59,318
6,Gowron,37,220
7,Will,54,307
8,Jadzia,38,380
9,Hugh,27,181
10,Odo,53,191
11,Ben,57,372
12,Keiko,54,253
13,Jean-Luc,56,444
14,Hugh,43,49
15,Rom,36,49
16,Weyoun,22,323
17,Odo,35,13
18,Jean-Luc,45,455
19,Geordi,60,246
20,Odo,67,220
21,Miles,19,268
22,Quark,30,72
23,Keiko,51,271
24,Julian,25,1
25,Ben,21,445
26,Julian,22,100
27,Leeta,42,363
28,Martok,49,476
29,Nog,48,364
30,Keiko,50,175
31,Miles,39,161
32,Nog,26,281
33,Dukat,53,197
34,Jean-Luc,43,249
35,Beverly,27,305
36,Kasidy,32,81
37,Geordi,58,21
38,Deanna,64,65
39,Morn,31,192
40,Odo,52,413
41,Hugh,67,167
42,Brunt,54,75
43,Guinan,58,345
44,Nerys,35,244
45,Dukat,52,77
46,Morn,25,96
47,Brunt,24,49
48,Nog,20,1
49,Ezri,40,254
50,Quark,51,283
51,Lwaxana,36,212
52,Beverly,19,269
53,Geordi,62,31
54,Brunt,19,5
55,Keiko,41,278
56,Gowron,44,194
57,Odo,57,294
58,Hugh,59,158
59,Morn,59,284
60,Geordi,20,100
61,Kasidy,62,442
62,Keiko,69,9
63,Jean-Luc,58,54
64,Elim,31,15
65,Guinan,52,169
66,Geordi,21,477
67,Jadzia,48,135
68,Guinan,33,74
69,Jean-Luc,30,204
70,Brunt,52,393
71,Geordi,45,184
72,Kasidy,22,179
73,Brunt,20,384
74,Leeta,65,208
75,Morn,40,459
76,Will,62,201
77,Weyoun,40,407
78,Data,61,337
79,Leeta,58,348
80,Dukat,67,445
81,Jadzia,54,440
82,Hugh,57,465
83,Geordi,32,308
84,Ben,28,311
85,Quark,66,383
86,Hugh,55,257
87,Ezri,31,481
88,Ben,66,188
89,Worf,24,492
90,Kasidy,33,471
91,Rom,46,88
92,Gowron,54,7
93,Elim,46,63
94,Morn,62,133
95,Odo,29,173
96,Ezri,25,233
97,Nerys,69,361
98,Will,44,178
99,Keiko,69,491
100,Jean-Luc,61,460
101,Morn,67,123
102,Dukat,40,18
103,Ezri,61,2
104,Dukat,32,142
105,Morn,50,417
106,Beverly,18,499
107,Will,64,419
108,Leeta,25,274
109,Quark,53,417
110,Nog,64,137
111,Nerys,37,46
112,Morn,25,13
113,Quark,41,244
114,Worf,33,275
115,Dukat,18,397
116,Ben,69,75
117,Rom,52,487
118,Ben,28,304
119,Worf,29,344
120,Jean-Luc,68,264
121,Deanna,35,355
122,Data,45,400
123,Jadzia,45,439
124,Data,47,429
125,Rom,66,284
126,Brunt,26,84
127,Miles,40,284
128,Julian,34,221
129,Kasidy,45,252
130,Gowron,67,350
131,Hugh,65,309
132,Odo,46,462
133,Quark,19,265
134,Ben,45,340
135,Rom,42,427
136,Will,19,335
137,Martok,28,32
138,Dukat,32,384
139,Nog,36,193
140,Elim,64,234
141,Miles,36,424
142,Guinan,59,335
143,Data,60,124
144,Miles,22,93
145,Leeta,45,470
146,Nerys,58,174
147,Quark,61,373
148,Nerys,39,248
149,Beverly,49,340
150,Nerys,55,313
151,Keiko,54,441
152,Kasidy,54,235
153,Morn,63,342
154,Geordi,40,389
155,Beverly,50,126
156,Deanna,44,360
157,Dukat,34,319
158,Odo,31,340
159,Kasidy,67,438
160,Beverly,58,112
161,Odo,39,207
162,Ezri,59,14
163,Nerys,67,204
164,Will,31,172
165,Leeta,26,282
166,Lwaxana,25,10
167,Quark,48,57
168,Martok,68,112
169,Beverly,53,92
170,Jean-Luc,68,490
171,Weyoun,29,126
172,Kasidy,55,204
173,Leeta,23,129
174,Deanna,47,87
175,Will,38,459
176,Worf,55,474
177,Brunt,67,316
178,Kasidy,26,381
179,Elim,37,426
180,Kasidy,30,108
181,Rom,43,404
182,Weyoun,26,145
183,Ben,47,488
184,Julian,44,84
185,Weyoun,48,287
186,Miles,31,109
187,Nerys,47,225
188,Keiko,54,369
189,Quark,62,23
190,Geordi,60,294
191,Nog,40,349
192,Jadzia,45,497
193,Nerys,60,125
194,Kasidy,38,2
195,Ben,30,376
196,Data,38,173
197,Leeta,38,76
198,Brunt,48,381
199,Hugh,38,180
200,Kasidy,21,472
201,Ezri,23,174
202,Lwaxana,63,469
203,Ezri,46,125
204,Deanna,64,164
205,Morn,69,236
206,Will,21,491
207,Lwaxana,41,206
208,Nog,37,271
209,Brunt,27,174
210,Data,33,245
211,Ben,61,73
212,Geordi,55,284
213,Worf,28,312
214,Miles,32,182
215,Will,22,6
216,Brunt,34,116
217,Keiko,29,260
218,Gowron,66,350
219,Lwaxana,26,345
220,Jean-Luc,41,394
221,Dukat,27,150
222,Rom,34,346
223,Odo,40,406
224,Keiko,44,277
225,Elim,19,106
226,Lwaxana,37,207
227,Ezri,40,198
228,Martok,26,293
229,Gowron,24,150
230,Beverly,54,397
231,Ezri,59,42
232,Worf,68,481
233,Gowron,67,70
234,Deanna,49,22
235,Elim,57,8
236,Brunt,62,442
237,Nerys,61,469
238,Deanna,25,305
239,Nog,48,345
240,Deanna,46,154
241,Quark,45,332
242,Data,25,101
243,Martok,61,68
244,Dukat,21,471
245,Jean-Luc,28,174
246,Leeta,41,260
247,Ezri,52,338
248,Dukat,21,138
249,Nerys,66,41
250,Hugh,36,342
251,Rom,55,57
252,Will,36,174
253,Leeta,69,116
254,Ezri,67,79
255,Deanna,60,324
256,Worf,32,412
257,Data,51,161
258,Worf,68,217
259,Kasidy,29,11
260,Brunt,38,96
261,Jadzia,40,172
262,Will,51,334
263,Martok,40,33
264,Julian,29,228
265,Gowron,27,471
266,Jean-Luc,66,496
267,Dukat,49,106
268,Ezri,26,298
269,Beverly,55,289
270,Data,44,353
271,Morn,25,446
272,Quark,29,367
273,Data,51,493
274,Julian,64,244
275,Will,47,13
276,Dukat,54,462
277,Hugh,46,300
278,Data,44,499
279,Beverly,23,133
280,Nerys,26,492
281,Worf,21,89
282,Geordi,32,404
283,Dukat,65,443
284,Nog,26,269
285,Data,43,101
286,Lwaxana,30,384
287,Beverly,64,396
288,Hugh,56,354
289,Ezri,30,221
290,Beverly,62,290
291,Dukat,23,373
292,Nog,63,380
293,Deanna,23,65
294,Leeta,38,410
295,Nerys,40,56
296,Data,38,454
297,Ben,45,395
298,Guinan,57,207
299,Rom,57,311
300,Beverly,49,147
301,Weyoun,28,108
302,Beverly,37,263
303,Deanna,46,319
304,Will,19,404
305,Quark,29,182
306,Beverly,23,323
307,Keiko,41,340
308,Morn,45,59
309,Geordi,67,153
310,Odo,68,189
311,Martok,43,48
312,Jadzia,61,421
313,Dukat,59,169
314,Geordi,36,168
315,Weyoun,25,208
316,Hugh,64,391
317,Guinan,59,439
318,Deanna,35,251
319,Leeta,30,476
320,Worf,62,450
321,Data,44,61
322,Rom,58,92
323,Nog,29,236
324,Miles,56,343
325,Keiko,51,492
326,Beverly,46,407
327,Julian,20,63
328,Deanna,62,41
329,Dukat,67,35
330,Ezri,33,356
331,Martok,30,17
332,Julian,55,362
333,Ben,29,207
334,Leeta,40,7
335,Odo,27,337
336,Gowron,47,4
337,Miles,58,10
338,Will,28,180
339,Morn,66,305
340,Nerys,57,275
341,Data,18,326
342,Guinan,46,151
343,Odo,26,254
344,Data,30,487
345,Ezri,31,394
346,Hugh,29,329
347,Geordi,32,24
348,Weyoun,33,460
349,Kasidy,20,277
350,Nog,55,464
351,Keiko,54,72
352,Deanna,27,53
353,Julian,64,499
354,Kasidy,69,15
355,Keiko,46,352
356,Weyoun,67,149
357,Brunt,26,7
358,Will,52,276
359,Nog,54,442
360,Nerys,39,68
361,Worf,68,206
362,Ezri,39,120
363,Dukat,41,397
364,Lwaxana,54,115
365,Brunt,65,430
366,Keiko,19,119
367,Data,39,106
368,Elim,26,383
369,Quark,48,266
370,Jadzia,53,86
371,Guinan,31,435
372,Brunt,62,273
373,Quark,19,272
374,Nog,68,293
375,Hugh,66,201
376,Gowron,23,392
377,Beverly,18,418
378,Guinan,47,97
379,Data,60,304
380,Brunt,35,65
381,Nog,38,95
382,Worf,66,240
383,Data,69,148
384,Martok,67,355
385,Beverly,57,436
386,Data,35,428
387,Will,43,335
388,Nog,30,184
389,Weyoun,38,38
390,Martok,22,266
391,Ben,64,309
392,Data,64,343
393,Quark,50,436
394,Keiko,23,230
395,Jean-Luc,56,15
396,Keiko,67,38
397,Quark,69,470
398,Lwaxana,26,124
399,Beverly,24,401
400,Data,29,128
401,Jean-Luc,42,467
402,Hugh,58,98
403,Weyoun,21,224
404,Kasidy,18,24
405,Nog,56,371
406,Ben,57,121
407,Miles,36,68
408,Dukat,62,496
409,Nog,19,267
410,Odo,35,299
411,Lwaxana,58,22
412,Jadzia,53,451
413,Hugh,45,147
414,Martok,56,313
415,Quark,30,65
416,Nerys,33,294
417,Julian,37,106
418,Guinan,32,212
419,Kasidy,55,176
420,Jadzia,26,391
421,Will,40,261
422,Ben,67,292
423,Will,44,388
424,Keiko,55,470
425,Quark,33,243
426,Worf,24,77
427,Brunt,28,258
428,Lwaxana,68,423
429,Jean-Luc,63,345
430,Geordi,36,493
431,Quark,36,343
432,Brunt,45,54
433,Ezri,38,203
434,Deanna,57,289
435,Guinan,42,275
436,Geordi,57,229
437,Morn,59,221
438,Nog,42,95
439,Data,18,417
440,Elim,48,394
441,Jadzia,38,143
442,Nog,46,105
443,Geordi,64,175
444,Keiko,18,472
445,Guinan,40,286
446,Quark,32,41
447,Julian,38,34
448,Nerys,48,439
449,Data,52,419
450,Weyoun,37,234
451,Martok,28,34
452,Ezri,58,6
453,Julian,44,337
454,Weyoun,52,456
455,Elim,33,463
456,Ezri,37,471
457,Worf,51,81
458,Elim,44,335
459,Geordi,26,84
460,Hugh,47,400
461,Geordi,41,236
462,Nerys,23,287
463,Keiko,40,220
464,Beverly,25,485
465,Morn,53,126
466,Brunt,33,228
467,Weyoun,42,194
468,Ezri,46,227
469,Brunt,55,271
470,Deanna,38,160
471,Brunt,52,273
472,Nog,27,154
473,Morn,35,38
474,Keiko,34,48
475,Ben,52,446
476,Jean-Luc,28,378
477,Gowron,50,119
478,Dukat,41,62
479,Kasidy,44,320
480,Geordi,43,428
481,Elim,32,97
482,Ben,48,146
483,Hugh,57,99
484,Leeta,22,478
485,Rom,47,356
486,Elim,49,17
487,Brunt,69,431
488,Nog,61,103
489,Odo,33,410
490,Nerys,65,101
491,Rom,60,2
492,Dukat,19,36
493,Hugh,23,357
494,Kasidy,18,194
495,Data,46,155
496,Gowron,39,275
497,Lwaxana,34,423
498,Jadzia,62,36
499,Leeta,62,12

In [31]:
PermTable = ''
df.write.format("parquet").saveAsTable('PermTable')

In [32]:
l = [('Alice','Ram')]

spark.createDataFrame(l,['name','age']).collect()
type(l)

In [33]:
rdd = sc.parallelize(l)
spark.createDataFrame(rdd,['name','age']).collect()

In [34]:
from pyspark.sql import Row
Person = Row('name','age')
person = rdd.map(lambda r: Person(*r))
spark.createDataFrame(person).collect()

In [35]:
from pyspark.sql.types import * 
schema = StructType([
  StructField('name', StringType(),True),
  StructField('age', StringType(),True)
])

df3 = spark.createDataFrame(rdd,schema)
df3.collect()

In [36]:
df = spark.createDataFrame([("a", 1), ("b", 2), ("c",  3)], ["Col1", "Col2"])
df.select(df.colRegex("`(Col1)?+.+`")).collect()

In [37]:
df.createGlobalTempView("friends")

In [38]:
df2 = spark.sql('select * from global_temp.friends')

In [39]:
sorted(df.collect()) == sorted(df2.collect())

In [40]:
spark.catalog.dropGlobalTempView("friends")

In [41]:
df.cube('Name',df.Age).count().orderBy("Name", "Age").collect()

In [42]:
df.select('Name').distinct().count()

In [43]:
df.distinct(df.Name).count()

In [44]:
df.na.drop().show()

In [45]:
df.filter(df.Age>18).collect()

In [46]:
df.where(df.Age >18).collect()

In [47]:
def f(p):
  print(p.Name)
df.foreach(f)

In [48]:
def f(people):
   for person in people:
      print(person.Name)

In [49]:
df.foreachPartition(f)

In [50]:
sorted(df.groupBy('Age').count().head())

In [51]:
df.isLocal()

In [52]:
df.isStreaming

In [53]:
df2 = df.alias('df2')

In [54]:
df.join(df2, df.Name == df2.Name, 'right_outer').select(df.Name).count()

In [55]:
cond = [df.Name == df2.Name, df.Age == df2.Age]

In [56]:
df.join(df2, cond, 'left_anti').select(df.Name).count()

In [57]:
df.limit(2).show()

In [58]:
df.sort('Age',ascending = False).collect()

In [59]:
df.orderBy(['Age','Friends'], ascending= [0,1] ).collect()

In [60]:
from pyspark.sql.functions import *

df.sort(asc("Age")).collect()

In [61]:
df.printSchema()

In [62]:
df.rdd.collect()

In [63]:
df.rdd.getNumPartitions()

In [64]:
df.repartition(2).rdd.getNumPartitions()

In [65]:
df.rollup('Name',df.Age).count().orderBy('Name','Age').show()

In [66]:
f = spark.range(10)

In [67]:
df.sample(fraction = 0.5,seed=3).count()

In [68]:
df.schema

In [69]:
df.select(df.Name,(df.Age+10).alias('age')).collect()

In [70]:
df.show()

In [71]:
df.toJSON().first()

In [72]:
 df.toPandas()

,Id,Name,Age,Friends
0,0,Will,33,385
1,1,Jean-Luc,26,2
2,2,Hugh,55,221
3,3,Deanna,40,465
4,4,Quark,68,21
5,5,Weyoun,59,318
6,6,Gowron,37,220
7,7,Will,54,307
8,8,Jadzia,38,380
9,9,Hugh,27,181
10,10,Odo,53,191
11,11,Ben,57,372
12,12,Keiko,54,253
13,13,Jean-Luc,56,444
14,14,Hugh,43,49
15,15,Rom,36,49
16,16,Weyoun,22,323
17,17,Odo,35,13
18,18,Jean-Luc,45,455
19,19,Geordi,60,246
20,20,Odo,67,220
21,21,Miles,19,268
22,22,Quark,30,72
23,23,Keiko,51,271
24,24,Julian,25,1
25,25,Ben,21,445
26,26,Julian,22,100
27,27,Leeta,42,363
28,28,Martok,49,476
29,29,Nog,48,364
...,...,...,...,...
470,470,Deanna,38,160
471,471,Brunt,52,273
472,472,Nog,27,154
473,473,Morn,35,38
474,474,Keiko,34,48
475,475,Ben,52,446
476,476,Jean-Luc,28,378
477,477,Gowron,50,119
478,478,Dukat,41,62
479,479,Kasidy,44,320
480,480,Geordi,43,428
481,481,Elim,32,97
482,482,Ben,48,146
483,483,Hugh,57,99
484,484,Leeta,22,478
485,485,Rom,47,356
486,486,Elim,49,17
487,487,Brunt,69,431
488,488,Nog,61,103
489,489,Odo,33,410
490,490,Nerys,65,101
491,491,Rom,60,2
492,492,Dukat,19,36
493,493,Hugh,23,357
494,494,Kasidy,18,194
495,495,Data,46,155
496,496,Gowron,39,275
497,497,Lwaxana,34,423
498,498,Jadzia,62,36
499,499,Leeta,62,12

In [73]:
df.withColumn('age2',df.Age + 2).collect()

In [74]:
df.select('Name', df.time.cast('timestamp')).withWatermark('time', '10 minutes')

In [75]:
from pyspark.sql.functions import *
df.groupBy('Name').1avg('Age').collect()

In [76]:
df5= df.repartition(2)

In [77]:
df5.rdd.getNumPartitions()

In [78]:
df5 = df5.coalesce(1)

In [79]:
df5.rdd.getNumPartitions()

In [80]:
df5.collect()

In [81]:
type(df.select(df.Age.astype('string')))

In [82]:
type(df.Age.astype('string'))

In [83]:
from pyspark.sql import Row 
df9 = spark.createDataFrame([Row(name='Tom', height=80), Row(name='Alice', height=None)])

In [84]:
df9.filter(df9.height.isNull()).collect()

In [85]:
from pyspark.sql.functions import *
df.write.format('parquet').bucketBy(100, 'age', 'name').mode('overwrite').saveAsTable('firstBucket')

In [86]:
df2 = spark.createDataFrame([('ABC',)], ['a'])

In [87]:
from pyspark.sql.functions import *
df2.select(sha2('a').alias('crc32')).collect()

In [88]:
dfdt = spark.createDataFrame([('2015-04-08',)], ['dt'])

In [89]:
dfdt.select(date_format('dt','MM/dd/yyyy').alias('prev_Date')).collect()

In [90]:
dfdt.select(date_sub(dfdt.dt,1).alias('prev_date')).collect()

In [91]:
dft = spark.createDataFrame([('1997-02-28 05:02:11',)], ['t'])

In [92]:
dft.select(date_trunc('quarter',dft.t).alias('month')).collect()

In [93]:
df = spark.createDataFrame([('2015-04-08','2015-05-10')], ['d1', 'd2'])

In [94]:
df.select(dayofmonth(df.d1).alias('dif')).collect()

In [95]:
from pyspark.sql import Row
eDF = spark.createDataFrame([Row(a=1, intlist=[1,2,3], mapfield={"a": "b"})])

In [96]:
eDF.select(explode(eDF.intlist).alias('anInt')).collect()

In [97]:
eDF.select(explode(eDF.mapfield).alias('key','value')).show()

In [98]:
 df9 = spark.createDataFrame([(1, ["foo", "bar"], 1), (2, [], {}), (3, None, None)],("id", "an_array", "a_map"))

In [99]:
df9.select('id','an_array', explode('a_map')).show()

In [100]:
df6 = spark.createDataFrame([([[1, 2, 3], [4, 5], [6]],), ([None, [4, 5]],)], ['data'])